### ISSUE TITLE
Firefox rendering issue

### ISSUE THREAD

**Issue by barche** [JuliaTeX/TikzPictures.jl#13]
Running the example from the readme in a notebook:
https://gist.github.com/barche/374acaa95b706e5b48b2

This renders correctly on github and using IJulia+safari, but in IJulia+firefox the text is missing:
![firefox-svg](https://cloud.githubusercontent.com/assets/966001/13668321/56536fb6-e6bc-11e5-84af-ba28e1594768.png)

I'm pretty sure this isn't a TikzPictures bug, but I have no idea where in the pipeline this can be fixed. Saving the embedded SVG code as a file and opening it in Firefox does render correctly, it is only when embedded in a notebook that it fails.

**Comment by mykelk** [comment]
I'm able to reproduce it on Windows. It fails on FireFox but works on Edge and Chrome.

**Comment by mykelk** [comment]
This works now on FireFox.
