### ISSUE TITLE
Display TikzPicture in Atom's Plots pane

### ISSUE THREAD

**Issue by mroavi** [JuliaTeX/TikzPictures.jl#35]
A nice feature would be to display TikzPictures in Atom's embedded Plots pane. Is there any support for that at the moment?

**Comment by mykelk** [comment]
Yeah, this would be nice. Is Atom pretty stable with Julia 1.0 now?

**Comment by mroavi** [comment]
I would say so. In my opinion, the best IDE to develop Julia code nowadays. The Plots package works great with Atom's Plots pane (using GR as backend).

**Comment by mykelk** [comment]
Cool. I was able to test this out. Do know what is involved in enabling this? I see some code mentioning Atom in [this](https://github.com/jheinen/GR.jl/blob/master/src/GR.jl). We're interested in PRs that would enable this.

**Comment by mroavi** [comment]
The Juno Documentation for the latest release explains how this can be done: [link](http://docs.junolab.org/latest/man/info_developer.html#Displaying-Plots-and-Graphics-1)

This code displays an SVG on the Plot pane:
```
struct Baz
    data
end

Base.show(io::IO, ::MIME"image/svg+xml", b::Baz) = print(io, b.data)
Baz(open(f -> read(f, String), "emu.svg"))
```
![plotpane_svg](https://user-images.githubusercontent.com/19517248/44629761-dbcfab80-a953-11e8-862a-770f1a2997b6.png)

**Comment by mykelk** [comment]
This works now. (Master only for the moment for Windows; but the release should be merged soon.)
