### ISSUE TITLE
Coveralls badge

### ISSUE THREAD

**Issue by mykelk** [JuliaTeX/TikzPictures.jl#37]
Any idea on why Coveralls stopped working when we moved to the JuliaTeX org?

**Comment by wangnangg** [comment]
Try adding `using Pkg;` to .travis.yml, i.e. from
```
julia -e 'cd(Pkg.dir("TikzPictures")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
```
to
```
julia -e 'using Pkg; cd(Pkg.dir("TikzPictures")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

```

**Comment by mykelk** [comment]
I added this, but according to the travis build [output](https://travis-ci.org/JuliaTeX/TikzPictures.jl/jobs/422382267), I think it is because coveralls is not turned on for this repo. I tried making my membership public and then refreshing the repo list, but the JuliaTeX repos do not show up. @tawheeler does it show up under your account after you make your membership of JuliaTeX public?

**Comment by tawheeler** [comment]
Coveralls is approved in the JuliaTeX 3rd party applications settings. I don't see it in Coveralls though.

**Comment by Shushman** [comment]
On a related matter, releasing the new version with my fixes did not trigger a pull request to `METADATA.jl` by attobot. Do you guys know what the next step is?

**Comment by tawheeler** [comment]
I do not. Maybe post a question on the Julia discourse?

**Comment by Shushman** [comment]
Yeah I'll investigate. I think `attobot` is not integrated with `JuliaTex`. Looking at the PRs in `METADATA.jl`, it seems that a few of the previous releases did not trigger PRs. I put in a request to install attobot on `JuliaTex`.

**Comment by tawheeler** [comment]
Aha! I enabled it. Please push a trivial PR to trigger it.

**Comment by Shushman** [comment]
Ah great. I can actually just re-release the new version and that should do it.
