### ISSUE TITLE
How can I add TikzPictures v3.0.1 though Pkg?

### ISSUE THREAD

**Issue by wangnangg** [JuliaTeX/TikzPictures.jl#40]
`add TikzPictures` will only give me v2.0.1

**Comment by mroavi** [comment]
> If the master branch (or a certain commit SHA) of Example has a hotfix that has not yet included in a registered version, we can explicitly track a branch (or commit) by appending #branch (or #commit) to the package name

Try:
```
(v0.7) pkg> up
(v0.7) pkg> add TikzPictures#v3.0.1
```
