### ISSUE TITLE
Error when saving an Image to .tex

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaTeX/TikzPictures.jl#43]
When saving a tikz picture that contains an image as a .tex file, the content of the .tex points to a temporary png file that is deleted. 

I will try to provide a MWE to reproduce the error.
@Shushman

**Comment by MaximeBouton** [comment]
This is a MWE using PGFPlots: 
```julia
using PGFPlots
f = (x,y)->x*exp(-x^2-y^2)
p = Plots.Image(f, (-2,2), (-2,2))
save("testimage.tex", p)
```

on ubuntu, through a jupyter notebook.

**Comment by mykelk** [comment]
I think in https://github.com/JuliaTeX/PGFPlots.jl/blob/master/src/PGFPlots.jl
lines 774 and 777 that have `cleanup(o)` should not be there.

@MaximeBouton can you verify and the commit the fix if so?

**Comment by MaximeBouton** [comment]
Commenting those lines indeed work! I will submit a PR to PGFPlots.
