### ISSUE TITLE
tikzset

### ISSUE THREAD

**Issue by Lecrapouille** [JuliaTeX/TikzPictures.jl#50]
Hi! Is this possible to add an extra parameter to `TikzPicture` in the aim to add code for `\tikzset{`?
For example to change the style for arrows:

```
\tikzset{myarrow/.style={->,draw=black,line width=1pt}}
```

LaTeX code to be placed before `\begin{tikzpicture}[`.

**Comment by Lecrapouille** [comment]
PS: If you wish I can create a PR!

**Comment by mykelk** [comment]
I think you can do this through the preamble. See [this](https://github.com/JuliaTeX/TikzPictures.jl/issues/49) for example. Do you have a more user friendly way in mind?

**Comment by Lecrapouille** [comment]
Thanks for your fast answer but preamble seems to placed before `\begin{document}` Is this really alright? Seem to be a little touchy to place tikz code before the document.

**Comment by mykelk** [comment]
Yep, I often put it before the start of the document and it works just fine.

**Comment by Lecrapouille** [comment]
Ok thanks I tried and effectively that it worked fine :) Just a last point. I'm writting a jupyther page but TikzPictures.jl create temporary directories `temp_dir = _mktempdir("./")`. Now I have so many folder inside my git project. I can add a .gitignore file but is it possible to create them in other folder for example /tmp ?

**Comment by mykelk** [comment]
If you look at the code [here](https://github.com/JuliaTeX/TikzPictures.jl/blob/master/src/TikzPictures.jl), it should be deleting the temp directories. If you can fix or narrow down the issue feel free to file another issue or PR. I'll close this one for now.
