### ISSUE TITLE
Path for files

### ISSUE THREAD

**Issue by harshangrjn** [JuliaTeX/TikzPictures.jl#51]
Is there a way to specify a particular path, something like `save(PDF("results/test"), tp)` instead of saving in the default folder? Currently I get an error of this form: `results/results: no such file or directory (ENOENT)`

**Comment by mykelk** [comment]
I think the directory has to exist. Does it in your case?

**Comment by harshangrjn** [comment]
I do have the "results" directory. But it throws an error about a folder which I haven't asked to save the file in. That's why, I was surprised.

**Comment by mykelk** [comment]
What's the output of `; pwd`?

**Comment by harshangrjn** [comment]
My current folder is `~/code`, where the script to generate the pdf is contained. And I also have the  `~/code/results` folder.

**Comment by mykelk** [comment]
It works for me:

![image](https://user-images.githubusercontent.com/6294079/72313287-c12cce00-363f-11ea-995b-937acaca39a1.png)
