### ISSUE TITLE
Emergency Stop

### ISSUE THREAD

**Issue by rcnlee** [JuliaTeX/TikzPictures.jl#54]
Hello, I get the following error when running the pgfplots example notebook.  But I basically get the same error with all codes that use TikzPictures.jl.  Any idea what it might be? I'm on Mac OS, Julia 1.4.  I suspect it might be an installation issue, but I don't have another machine to test it on at the moment.  Thanks!

```
> x = [1,2,3]
> y = [2,4,1]
> plot(x, y)
```
```
TikzPictures.TikzPicture("\\begin{axis}\\addplot+ coordinates {\n(1, 2)\n(2, 4)\n(3, 1)\n};\n\\end{axis}\n", "", "\\usepackage{pgfplots}\n\\pgfplotsset{compat=newest}\n\\pgfplotsset{every axis legend/.append style={%\ncells={anchor=west}}\n}\n\\usetikzlibrary{arrows}\n\\tikzset{>=stealth'}\n", true)
! Emergency stop.
<everyjob> ...ring \\def\string \\encodingdefault{OT1}')end }
                                                  \let \f@encoding \encoding...
l.1 
  \documentclass[tikz]{standalone}
End of file on the terminal!



Here is how much of LuaTeX's memory you used:
 8 strings out of 494300
 100000,89155 words of node,token memory allocated 241 words of node memory still in use:
   1 dir, 34 glue_spec nodes
   avail lists: 2:12,3:1,4:1
 4357 multiletter control sequences out of 65536+600000
 14 fonts using 591799 bytes
 5i,0n,1p,61b,15s stack positions out of 5000i,500n,10000p,200000b,100000s
!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by mykelk** [comment]
I think there was an issue with the lualatex that shipped with texlive 2018. See [this](https://tex.stackexchange.com/questions/448832/problems-with-luatex-1-08-even-on-a-very-simple-document). You might want to just update to texlive 2020.

**Comment by rcnlee** [comment]
Thank you! I upgraded the texlive and texlive-latex-extra packages via macports and it works now.
