### ISSUE TITLE
Customize environment for TikZ picture

### ISSUE THREAD

**Issue by epatters** [JuliaTeX/TikzPictures.jl#58]
Would it be possible to add a field to `TikzPicture` that allows the LaTeX environment for TikZ pictures to be changed? My use case is [tikz-cd](https://ctan.org/pkg/tikz-cd), which uses the environment `\begin{tikzcd} .. \end{tikzcd}` instead of `\begin{tikzpicture} ... \end{tikzpicture}`.

I can implement this feature if you think it makes sense.

**Comment by mykelk** [comment]
I'm open to it! Are there other use cases that you are aware of beyond tikz-cd?

**Comment by epatters** [comment]
Great! At the moment I can't think of any other uses cases.

**Comment by mykelk** [comment]
No prob. Feel free to send in a PR. It should be fine so long as the current API doesn't break.
