### ISSUE TITLE
Tag New Release With Custom Environments

### ISSUE THREAD

**Issue by mehalter** [JuliaTeX/TikzPictures.jl#62]
Hey, I noticed you incrementd the project version after the new Environments addition, when will this release be tagged and available? This feature will be necessary for the new TikzCDs.jl package. Thanks again for all your help!

**Comment by mykelk** [comment]
Yep, we're working on getting it merged into the registry. We're running into a snag at the moment though, which @MaximeBouton is looking at.

**Comment by MaximeBouton** [comment]
the PR is here if you want to follow the status: https://github.com/JuliaRegistries/General/pull/20417

**Comment by MaximeBouton** [comment]
It should be good now!
