### ISSUE TITLE
Standalone workaround does not trigger

### ISSUE THREAD

**Issue by schillic** [JuliaTeX/TikzPictures.jl#65]
The workaround for `standalone` catches a specific error message:

https://github.com/JuliaTeX/TikzPictures.jl/blob/34dfc43aaa7f1a983af8ea23cd4996f4dc958dcf/src/TikzPictures.jl#L258

For me the error message differs and hence the workaround does not kick in:

```
\sa@placebox ...wd \sa@box \global \pdfpageheight
```

I tried on two different systems (Ubuntu and Fedora) and got the same error. I can of course work around this by manually enabling the workaround. But maybe you could consider generalizing the filter (I guess replacing `->\\newpage` by a wildcard should do the trick).

**Comment by mykelk** [comment]
Ah, interesting! Yes, feel free to file a PR with that filter. We don't want it to be too broad though, but what you describe seems okay. Which version of texlive are you running?

**Comment by schillic** [comment]
> feel free to file a PR with that filter

Alright, probably in the next days :snail:

> Which version of texlive are you running?

Ubuntu: 2017; Fedora: 2019

**Comment by schillic** [comment]
Sorry, this was a wrong report. I do get the same substring in the error message, so the issue is somewhere else.
For context, I want to use [`TreeView`](https://github.com/JuliaTeX/TreeView.jl), which uses [`TikzGraphs`](https://github.com/JuliaTeX/TikzGraphs.jl) for printing a tikz picture in a notebook. Somewhere in this pipeline there seems to be a problem for me (for at least one other person it seems to work). But I give up now and just always do this:

```julia
using TreeView
using TikzPictures  # workaround
TikzPictures.standaloneWorkaround(true)  # workaround
@tree exp(x^4 + 2) - x^3
```
