### ISSUE TITLE
Why is limit_to not exposed for TIKZ

### ISSUE THREAD

**Issue by H-M-H** [JuliaTeX/TikzPictures.jl#69]
I tend to use `\includegraphics` for TIKZ pictures a lot but in this case I need them without preamble but with the `.tikz` file ending. Is there a reason why limit_to is set to `:all` only?
https://github.com/JuliaTeX/TikzPictures.jl/blob/5bca9c2856e06cbf4f7a1a9231b05ef265b06bee/src/TikzPictures.jl#L101-L105

I can workaround this by changing limit_to after creating a TIKZ object and this seems to work just fine.

**Comment by mykelk** [comment]
Feel free to file a PR where we can pass in an optional argument.

**Comment by H-M-H** [comment]
Alright, have a look at #70 then.

**Comment by mykelk** [comment]
Thanks!
