### ISSUE TITLE
Use jll binary

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaTeX/TikzPictures.jl#75]
Tectonic is packaged as a Julia jll binary (via [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil)) and could most likely solve a lot of problems people are having with TikzPictures. When using Tectonic like
```
Tectonic.tectonic() do tectonic_bin
     run(`$tectonic_bin paper.tex`)
end
```
all the required artefacts are managed by Julia and Tectonic.

For example, I'm using Tectonic for my package [Books.jl](https://github.com/rikhuijzer/Books.jl) and due to it, I don't have to install LaTeX in the CI job. Julia handles it for me and the users.

**Comment by rikhuijzer** [comment]
Let me know if this sounds like a good idea, then I'll send in a PR.

**Comment by mykelk** [comment]
Nice! Let's do it! Let's have it as the default if `lualatex -v` fails, and make it switchable as well (just like the use of the poppler backend).

**Comment by mykelk** [comment]
Done! Thanks for the idea!
