### ISSUE TITLE
Failure to precompile do to Tectonic issue

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaTeX/TikzPictures.jl#82]
The issue https://github.com/MichaelHatherly/Tectonic.jl/issues/13, prevents Tectonic from precompiling on M1 Macs until an upstream tectonic issue is resolved. Is there a way to prevent that precompile issue from propagating to TikzPictures?

From looking at the TikzPictures src, it appears that lualatex is the default engine with Tectonic being opt-in.

**Comment by jpfairbanks** [comment]
Upstream says that we can use a JLL version if we don't need biber support. Would switching to that help? 

https://github.com/MichaelHatherly/Tectonic.jl/issues/13#issuecomment-1230254674

**Comment by mykelk** [comment]
We don't need biber support.

**Comment by adrienbanse** [comment]
Hi @jpfairbanks @mykelk
Any progress on this? I'm not able to precompile TikzPictures on my M2 mac because of Tectonic, is there any workaround?

**Comment by mykelk** [comment]
@dylan-asmar is looking into this.
